import NoteSidebar from "./components/notesidebar";
import Sidebar from "./components/sidebar";
import "./globals.css";
import { Source_Sans_3 } from "next/font/google";

const inter = Source_Sans_3({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          {/* Sidebar for folders */}
          <Sidebar />

          <div className="flex-grow">
            {/* Sidebar for notes within a folder */}
   
            {/* Main content area for displaying notes */}
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
